# Plex Metadata Generator & Asset Downloader Configuration Template

# Dry run
dry_run: false

# Logging
log_level: "INFO"

# Plex server configuration
plex:
  url: "http://your-plex-server:32400"
  token: "YOUR_PLEX_TOKEN"

# TMDb API configuration
tmdb:
  api_key: "YOUR_TMDB_API_KEY"
  language: "en"
  region: "US"
  fallback:
    - zh
    - ja
    - fr

# Plex libraries to process
preferred_libraries:
  - Movies
  - TV Shows

# Metadata and asset processing options
process_metadata: true
enhanced_metadata: true
process_assets: true
process_season_posters: true
process_backgrounds: true
cleanup_orphans: true

# Metadata and Assets path
metadata_path: "/path/to/metadata/"
assets_path: "/path/to/assets/"
upgrade_schedule:
  frequency: "daily"        # Options: daily, twice_a_week, weekly, monthly, custom
  days: [1, 4]              # Examples for week/month frequency: 1=Monday, 4=Thursday
  times: 4                  # For custom: how many times per month

# Poster selection preferences (Only if process_posters is true)
poster_selection:
  preferred_width: 2000
  preferred_height: 3000
  min_width: 1000
  min_height: 1500
  preferred_vote: 5.0
  vote_relaxed: 3.5
  vote_average_threshold: 5.0

# Background selection preferences (Only if process_backgrounds is true)
background_selection:
  preferred_width: 3840
  preferred_height: 2160
  min_width: 1920
  min_height: 1080
  preferred_vote: 5.0
  vote_relaxed: 3.5
  vote_average_threshold: 5.0
