# Plex Metadata Generator & Asset Downloader Configuration Template

# Force run of MetaFusion
metafusion_run: false

# Dry run and logging configuration
settings:
  schedule: true
  run_times:
    - "06:00"
    - "18:30"
  dry_run: false
  log_level: "INFO"
  mode: "kometa"  # or "plex"
  path: "/kometa"

# Plex server configuration
plex:
  url: "http://10.0.0.1:32400"
  token: "YOUR_PLEX_TOKEN"

# Plex libraries to process
plex_libraries:
  - Movies
  - TV Shows

# TMDb API configuration
tmdb:
  api_key: "YOUR_TMDB_API_KEY"
  language: "en"
  region: "US"
  fallback:
    - zh
    - ja
    - fr

# Metadata and asset processing options
metadata:
  run_basic: true
  run_enhanced: true

assets:
  run_poster: true
  run_season: true
  run_background: false

cleanup:
  run_process: true

# Poster selection preferences (Only if run_poster is true)
poster_set:
  max_width: 2000
  max_height: 3000
  min_width: 1000
  min_height: 1500
  prefer_vote: 5.0
  vote_relaxed: 3.5
  vote_threshold: 5.0

# Season poster selection preferences (Only if run_season is true)
season_set:
  max_width: 2000
  max_height: 3000
  min_width: 1000
  min_height: 1500
  prefer_vote: 5.0
  vote_relaxed: 0.5
  vote_threshold: 3.0 
  
# Background selection preferences (Only if run_background is true)
background_set:
  max_width: 3840
  max_height: 2160
  min_width: 1920
  min_height: 1080
  prefer_vote: 5.0
  vote_relaxed: 3.5
  vote_threshold: 5.0
