# Plex Metadata Generator & Asset Downloader Configuration Template

# Plex server configuration
plex:
  url: "http://your-plex-server:32400"
  token: "YOUR_PLEX_TOKEN"

# TMDb API configuration
tmdb:
  api_key: "YOUR_TMDB_API_KEY"
  language: "en"
  region: "US"
  fallback:
    - zh
    - ja
    - fr

# Dry run
dry_run: false

# Plex libraries to process
preferred_libraries:
  - Movies
  - TV Shows

# Metadata & Asset processing
process_metadata: true
process_assets: true
process_season_posters: true
process_backgrounds: true
process_season_backgrounds: true
cleanup_orphans: true

# Logging
log_level: "INFO"

# Threading
threads:
  max_workers: 20
  timeout: 300

# Metadata output
metadata_path: "/path/to/metadata/"

# Asset management
assets_path: "/path/to/assets/"

# Poster selection preferences
poster_selection:
  preferred_width: 2000
  preferred_height: 3000
  min_width: 1000
  min_height: 1500
  preferred_vote: 5.0
  vote_relaxed: 3.5
  vote_average_threshold: 5.0

# Background selection preferences
background_selection:
  preferred_width: 3840
  preferred_height: 2160
  min_width: 1920
  min_height: 1080
  preferred_vote: 5.0
  vote_relaxed: 3.5
  vote_average_threshold: 5.0
