# Plex Metadata Generator & Asset Downloader Configuration Template

# Plex server configuration
plex:
  url: "http://your-plex-server:32400"
  token: "YOUR_PLEX_TOKEN"

# TMDb API configuration
tmdb:
  api_key: "YOUR_TMDB_API_KEY"
  language: "en"
  region: "US"
  fallback:
    - zh
    - ja
    - fr

# Plex libraries to process
preferred_libraries:
  - Movies
  - TV Shows
process_libraries: true
cleanup_orphans: true

# Metadata & Asset processing
process_metadata: true
process_assets: true
process_season_posters: true

# Logging
log_level: "INFO"

# Threading
threads:
  max_workers: 5
  timeout: 300

# Metadata output
metadata_path: "/path/to/metadata/"

# Asset management
assets_path: "/path/to/assets/"

# Poster selection preferences
poster_selection:
  preferred_width: 2000
  preferred_height: 3000
  min_width: 1000
  min_height: 1500
  preferred_vote: 5.0
  vote_relaxed: 3.5
  vote_average_threshold: 5.0

# Network and retry settings
network:
  backoff_factor: 1
  max_retries: 3
  timeout: 10
  pool_connections: 100
  pool_maxsize: 100

# Dry run
dry_run: false