version: "3.8"
services:
  metafusion:
    image: ghcr.io/ray-cys/metafusion:main
    container_name: metafusion
    environment:
      - CONFIG_DIR=/config
      - KOMETA_PATH=/kometa
      - PLEX_URL=http://10.0.0.1:32400
      - PLEX_TOKEN=YOUR_PLEX_TOKEN
      - PLEX_LIBRARIES=Movies,TV Shows
      - TMDB_API_KEY=YOUR_TMDB_API_KEY
      - TMDB_LANGUAGE=en
      - TMDB_REGION=US
      - TMDB_LANGUAGE_FALLBACK=zh,ja
      - RUN_MODE=kometa
      - DRY_RUN=False
      - RUN_SCHEDULE=True
      - RUN_TIMES=06:00,18:30
      - LOG_LEVEL=INFO
      - RUN_BASIC=True
      - RUN_ENHANCED=True
      - RUN_POSTER=True
      - RUN_SEASON=True
      - RUN_BACKGROUND=False
      - RUN_PROCESS=True
      - POSTER_MAX_WIDTH=2000
      - POSTER_MAX_HEIGHT=3000
      - POSTER_MIN_WIDTH=1000
      - POSTER_MIN_HEIGHT=1500
      - POSTER_PREFER_VOTE=5.0
      - POSTER_VOTE_RELAXED=3.5
      - POSTER_VOTE_THRESHOLD=5.0
      - SEASON_MAX_WIDTH=2000
      - SEASON_MAX_HEIGHT=3000
      - SEASON_MIN_WIDTH=1000
      - SEASON_MIN_HEIGHT=1500
      - SEASON_PREFER_VOTE=5.0
      - SEASON_VOTE_RELAXED=0.5
      - SEASON_VOTE_THRESHOLD=3.0
      - BG_MAX_WIDTH=3840
      - BG_MAX_HEIGHT=2160
      - BG_MIN_WIDTH=1920
      - BG_MIN_HEIGHT=1080
      - BG_PREFER_VOTE=5.0
      - BG_VOTE_RELAXED=3.5
      - BG_VOTE_THRESHOLD=5.0
    volumes:
      - ./config:/config
      - ./kometa:/kometa
    restart: unless-stopped